### ISSUE TITLE
Request to Client fails | java.lang.NoSuchFieldError: SAMPLING_PRIORITY

### ISSUE THREAD

**Issue by tosheer** [stagemonitor/boot-zipkin#3]
After doing setup as the document. All the request to http://localhost:8080/ is failing with error.

```
2018-02-22 09:34:02.955 ERROR 21339 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Filter execution threw an exception] with root cause

java.lang.NoSuchFieldError: SAMPLING_PRIORITY
	at org.stagemonitor.tracing.SpanContextInformation$SpanContextSpanEventListener.handleTagsSetBeforeSpanStarted(SpanContextInformation.java:260) ~[stagemonitor-tracing-0.80.0-20170709.123341-2.jar:0.80.0.SNAPSHOT]
	at org.stagemonitor.tracing.SpanContextInformation$SpanContextSpanEventListener.onStart(SpanContextInformation.java:255) ~[stagemonitor-tracing-0.80.0-20170709.123341-2.jar:0.80.0.SNAPSHOT]
	at org.stagemonitor.tracing.wrapper.SpanWrappingTracer$SpanWrappingSpanBuilder.start(SpanWrappingTracer.java:146) ~[stagemonitor-tracing-0.80.0-20170709.123341-2.jar:0.80.0.SNAPSHOT]
	at org.stagemonitor.web.monitor.MonitoredHttpRequest.createSpan(MonitoredHttpRequest.java:90) ~[stagemonitor-web-0.80.0-20170530.074945-3.jar:0.80.0.SNAPSHOT]
	at org.stagemonitor.tracing.RequestMonitor.monitorStart(RequestMonitor.java:37) ~[stagemonitor-tracing-0.80.0-20170709.123341-2.jar:0.80.0.SNAPSHOT]
	at org.stagemonitor.tracing.RequestMonitor.monitor(RequestMonitor.java:59) ~[stagemonitor-tracing-0.80.0-20170709.123341-2.jar:0.80.0.SNAPSHOT]
	at org.stagemonitor.web.monitor.filter.HttpRequestMonitorFilter.monitorRequest(HttpRequestMonitorFilter.java:166) ~[stagemonitor-web-0.80.0-20170530.074945-3.jar:0.80.0.SNAPSHOT]
	at org.stagemonitor.web.monitor.filter.HttpRequestMonitorFilter.doMonitor(HttpRequestMonitorFilter.java:129) ~[stagemonitor-web-0.80.0-20170530.074945-3.jar:0.80.0.SNAPSHOT]
	at org.stagemonitor.web.monitor.filter.HttpRequestMonitorFilter.doFilterInternal(HttpRequestMonitorFilter.java:102) ~[stagemonitor-web-0.80.0-20170530.074945-3.jar:0.80.0.SNAPSHOT]
	at org.stagemonitor.web.monitor.filter.AbstractExclusionFilter.doFilter(AbstractExclusionFilter.java:75) ~[stagemonitor-web-0.80.0-20170530.074945-3.jar:0.80.0.SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_152]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
```

let me know if i am missing anything. 

I have also tried upgrading it to the new version, but that also failed.

```
<dependency>
			<groupId>org.stagemonitor</groupId>
			<artifactId>stagemonitor-web-servlet</artifactId>
			<version>0.87.5</version>
		</dependency>
		<dependency>
			<groupId>org.stagemonitor</groupId>
			<artifactId>stagemonitor-tracing-zipkin</artifactId>
			<version>0.80.0.RC1</version>
		</dependency>
```

**Comment by trampi** [comment]
Hi @tosheer,

all stagemonitor dependencies need to be the same version. Try `stagemonitor-tracing-zipkin` with version 0.87.5 instead.

**Comment by tosheer** [comment]
@trampi for stagemonitor-tracing-zipkin 0.87.5  doesn't exists.

http://repo1.maven.org/maven2/org/stagemonitor/stagemonitor-tracing-zipkin/
